# Generated by Django 6.0.4 on 2026-04-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold / Waiting'), ('review', 'Client Review'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
