# Generated by Django 6.0.4 on 2026-04-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_backfill_tasklists'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
