# Generated by Django 6.0.4 on 2026-04-20 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_alter_taskcomment_options_timeentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=60)),
                ('color', models.CharField(default='gray', max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_done', models.BooleanField(default=False)),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='workspaces.tasklist')),
            ],
            options={
                'ordering': ['position', 'id'],
                'unique_together': {('task_list', 'key')},
            },
        ),
    ]
