# Generated by Django 6.0.4 on 2026-04-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0011_seed_default_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='color',
            field=models.CharField(default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='list_images/'),
        ),
    ]
