# Generated by Django 6.0.4 on 2026-04-29 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0013_workspacemember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('field_type', models.CharField(choices=[('dropdown', 'Dropdown'), ('labels', 'Labels'), ('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('checkbox', 'Checkbox'), ('url', 'URL'), ('email', 'Email')], default='dropdown', max_length=20)),
                ('visible_to_guests', models.BooleanField(default=True)),
                ('is_private', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_fields_created', to=settings.AUTH_USER_MODEL)),
                ('lists', models.ManyToManyField(blank=True, related_name='custom_fields', to='workspaces.tasklist')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('color', models.CharField(default='gray', max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='workspaces.customfield')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('view', 'Can view'), ('edit', 'Can edit')], default='edit', max_length=10)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='workspaces.customfield')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('field', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TaskCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True, default='')),
                ('number_value', models.FloatField(blank=True, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('bool_value', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='workspaces.customfield')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_values', to='workspaces.customfieldoption')),
                ('options', models.ManyToManyField(blank=True, related_name='task_values_multi', to='workspaces.customfieldoption')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_values', to='workspaces.task')),
            ],
            options={
                'unique_together': {('task', 'field')},
            },
        ),
    ]
