# Generated by Django 6.0.4 on 2026-04-29 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0014_customfield_customfieldoption_customfieldpermission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.CharField(choices=[('list', 'List'), ('board', 'Board'), ('calendar', 'Calendar'), ('gantt', 'Gantt')], default='list', max_length=20)),
                ('show_empty_statuses', models.BooleanField(default=True)),
                ('wrap_text', models.BooleanField(default=False)),
                ('show_task_locations', models.BooleanField(default=False)),
                ('show_subtask_parent_names', models.BooleanField(default=True)),
                ('show_closed_tasks', models.BooleanField(default=True)),
                ('subtasks_mode', models.CharField(choices=[('collapsed', 'Collapsed'), ('expanded', 'Expanded'), ('separate', 'As separate tasks')], default='collapsed', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('autosave_for_me', models.BooleanField(default=True)),
                ('protected', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_preferences', to='workspaces.tasklist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'task_list', 'view')},
            },
        ),
    ]
