# Generated by Django 6.0.4 on 2026-04-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0016_channel_channelmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='purpose',
            field=models.CharField(blank=True, choices=[('work', 'Work'), ('personal', 'Personal'), ('school', 'School')], default='', max_length=20),
        ),
    ]
