# Generated by Django 6.0.4 on 2026-04-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0017_workspace_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='is_global',
            field=models.BooleanField(default=False, help_text='Available on every list in every workspace this user can see'),
        ),
    ]
