# Generated by Django 6.0.4 on 2026-05-02 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0018_customfield_is_global'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelmessage',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='channelmessage',
            name='author',
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='ChannelMessage',
        ),
    ]
