# Generated by Django 6.0.5 on 2026-05-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0019_remove_channelmessage_channel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeentry',
            options={'ordering': ['-started_at']},
        ),
        migrations.AddField(
            model_name='timeentry',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
