# Generated by Django 6.0.5 on 2026-05-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0022_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, choices=[('administration', 'Administration'), ('development', 'Development'), ('design', 'Design'), ('meetings', 'Meetings'), ('research', 'Research'), ('support', 'Support'), ('strategy', 'Strategy'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='purpose',
            field=models.CharField(blank=True, choices=[('project', 'Project'), ('retainer', 'Retainer'), ('internal', 'Internal')], default='', max_length=20),
        ),
    ]
