# Generated by Django 6.0.5 on 2026-05-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0023_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='recur_forever',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_action',
            field=models.CharField(blank=True, choices=[('create_new', 'Create new task'), ('reopen', 'Reopen this task')], default='create_new', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_count',
            field=models.PositiveIntegerField(blank=True, help_text='Repeat X times (null = forever)', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_days',
            field=models.CharField(blank=True, default='', help_text='Comma-separated day numbers for weekly: 0=Mon..6=Sun', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('days_after', 'Days After'), ('custom', 'Custom')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_interval',
            field=models.PositiveIntegerField(default=1, help_text='Every X days/weeks/months/years'),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_status_reset',
            field=models.CharField(blank=True, default='', help_text='Reset to this status on recurrence', max_length=40),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_trigger',
            field=models.CharField(blank=True, choices=[('on_complete', 'When status set to Done'), ('on_schedule', 'On a schedule')], default='on_complete', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='sync_recurrence_to_due',
            field=models.BooleanField(default=True),
        ),
    ]
