# Generated by Django 6.0.5 on 2026-05-09 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0024_recurring_task_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subtasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subtask',
            name='category',
            field=models.CharField(blank=True, choices=[('administration', 'Administration'), ('development', 'Development'), ('design', 'Design'), ('meetings', 'Meetings'), ('research', 'Research'), ('support', 'Support'), ('strategy', 'Strategy'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='subtask',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold / Waiting'), ('review', 'Client Review'), ('internal_review', 'Internal Review'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
