# Generated by Django 6.0.5 on 2026-05-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0027_migrate_assignee_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
    ]
