# Generated by Django 6.0.5 on 2026-05-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0030_migrate_subtask_assignee_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='assignee',
        ),
    ]
