# Generated by Django 6.0.5 on 2026-05-15 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0031_remove_subtask_assignee_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('name', models.CharField(max_length=60)),
                ('color', models.CharField(default='blue', max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['position', 'name'],
                'unique_together': {('workspace', 'key')},
            },
        ),
    ]
