# Generated by Django 6.0.5 on 2026-05-15 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0032_category_model'),
    ]

    operations = [
    ]
