# Generated by Django 6.0.5 on 2026-05-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0034_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
