# Generated by Django 6.0.5 on 2026-05-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0037_dashboardcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
