# Generated by Django 6.0.5 on 2026-05-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0040_report_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workspace_images/'),
        ),
    ]
