# Generated by Django 6.0.5 on 2026-05-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0042_org_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='card_layout',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
