# Generated by Django 6.0.5 on 2026-05-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0044_rename_internal_to_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='purpose',
            field=models.CharField(blank=True, choices=[('work', 'Work'), ('project', 'Project'), ('retainer', 'Retainer'), ('personal', 'Personal')], default='', max_length=20),
        ),
    ]
