# Generated by Django 6.0.5 on 2026-05-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0045_add_work_purpose_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='purpose',
            field=models.CharField(blank=True, choices=[('project', 'Project'), ('retainer', 'Retainer'), ('personal', 'Personal')], default='', max_length=20),
        ),
    ]
