# Generated by Django 6.0.5 on 2026-05-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0047_task_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='color',
            field=models.CharField(default='blue', max_length=20),
        ),
    ]
