# Generated by Django 6.0.5 on 2026-05-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0048_workspace_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcard',
            name='col_span',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='dashboardcard',
            name='row_span',
            field=models.IntegerField(default=4),
        ),
    ]
