# Generated by Django 6.0.5 on 2026-05-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0049_dashboardcard_resize_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardcard',
            name='col_span',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='dashboardcard',
            name='row_span',
            field=models.IntegerField(default=280),
        ),
    ]
