# Generated by Django 6.0.5 on 2026-05-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0050_dashboardcard_resize_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcard',
            name='x_pos',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='dashboardcard',
            name='y_pos',
            field=models.IntegerField(default=-1),
        ),
    ]
