# Generated by Django 6.0.5 on 2026-05-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0052_add_dashboard_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcard',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='dashboard/cards/'),
        ),
        migrations.AddField(
            model_name='dashboardpreference',
            name='bg_image',
            field=models.ImageField(blank=True, default='', upload_to='dashboard/bg/'),
        ),
    ]
