# Generated by Django 6.0.5 on 2026-05-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_role_alter_user_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager')], default='user', help_text='User role in the system', max_length=20),
        ),
    ]
